import type { ViewerState } from "./types";

export const state: ViewerState = {
  offset: 0,
  limit: 30,
  total: 0,
  items: [],
  query: "",
  tags: [],
  tagSuggestionsRequestId: 0,
  folderId: "",
  ext: "",
  rating: "",
  filtersOpen: false,
  folders: [],
  viewMode: "grid",
  tilesLoadingMore: false,
  tilesObserver: null,
  requestId: 0,
  previewTransform: {
    scale: 1,
    x: 0,
    y: 0,
  },
  previewFitScale: 1,
  previewNaturalScale: 1,
  previewDrag: null,
  previewPointers: new Map(),
  previewPinch: null,
  previewItemId: "",
  previewInfoOpen: false,
  restoringHistory: false,
};
